### ISSUE TITLE
update_from_db.py error

### ISSUE THREAD

**Issue by ImNtReal** [Zeg9/minetest-skins#8]
When I try to run update_from_db.py for the first time, I'm getting:
Traceback (most recent call last):
  File "./update_from_db.py", line 39, in <module>
    addpage(p+2)
  File "./update_from_db.py", line 16, in addpage
    r = c.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

**Comment by MarkR84** [comment]
I'm getting this too, python 3.4:

`Traceback (most recent call last):
  File "update_from_db.py", line 39, in <module>
    addpage(p+2)
  File "update_from_db.py", line 16, in addpage
    r = c.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''`
